// packages/ui-react/src/components/Interactive.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { numberToHex, isHex, stringToHex, isAddress, keccak256, type Hex } from 'viem'
import {
  useChainStore,
  selectChain,
  selectName,
  selectRpcUrl,
  selectTransportUrl,
  selectFullTransportUrl,
  selectRpcValid,
  selectFaucetIsActive,
} from '../stores/chain'
import type { ChainOption } from '../lib/rpc'
import { useTerminalStore, Log, selectMessageList } from '../stores/terminal'
import { useAccount } from '../hooks/useAccount'
import { getScope, load, save, collectLabels } from '../lib/persist'
import { toTree } from '../lib/tree'
import { makeWorkerBoard } from '../seams/worker-board'
import { SelectChain } from './SelectChain'
import { Category } from './Category'
import { MessageInput } from './MessageInput'
import { PresetButtons } from './PresetButtons'
import { Summary } from './Summary'
import { Terminal } from './Terminal'
import { TreeView, loadTreeNodeState, pruneTreeNodeState } from './TreeView'
import { RequestSnapshot, type WorkSnapshot } from './RequestSnapshot'

type CategoryKey = 'gas-request' | 'input'
type InteractiveState = {
  categoryType: CategoryKey
  categoryValue: string
  text: string
  showHexResult: boolean
  showCategoryHexResult: boolean
  useKeccak: boolean
}

type Props = {
  /**
   * Worker factory passed through to the PoW seam — injectable so headless tests can supply a
   * fake `Worker`. Production omits it (the seam spawns the default ES-module PoW worker).
   * The grind ALWAYS runs in that worker — never the main thread.
   */
  workerFactory?: () => Worker
}

const scopeFromStore = (): string => {
  const s = useChainStore.getState()
  return getScope(selectChain(s)?.id, selectRpcUrl(s))
}

/**
 * Ported from `Interactive.svelte` — the MVP vertical slice.
 *
 * Compose a message → grind PoW in the Web Worker seam (Task 2) → the worker posts it → reload
 * board content (chain store) → Terminal + TreeView render. The grind is dispatched to the
 * worker via `makeWorkerBoard.addMessage`; it NEVER runs on the main thread.
 */
export function Interactive({ workerFactory }: Props) {
  // chain-store reads (each a former Svelte `$derived`)
  const transportUrl = useChainStore((s) => selectTransportUrl(s))
  const fullTransportUrl = useChainStore((s) => selectFullTransportUrl(s))
  const chainId = useChainStore((s) => selectChain(s)?.id ?? 0)
  const chainName = useChainStore((s) => selectName(s) ?? 'Unknown')
  const rpcValid = useChainStore((s) => selectRpcValid(s))
  const faucetIsActive = useChainStore((s) => selectFaucetIsActive(s))
  const loading = useChainStore((s) => s.loading)
  const content = useChainStore((s) => s.content)
  const latestBlockNumber = useChainStore((s) => s.latestBlockNumber)
  const globalWorkMultiplier = useChainStore((s) => s.globalWorkMultiplier)
  const globalWorkDivisor = useChainStore((s) => s.globalWorkDivisor)

  const account = useAccount()

  const initialScope = scopeFromStore()
  const stored = load<Partial<InteractiveState>>(initialScope, 'interactive', {})

  const [text, setText] = useState(stored.text ?? '')
  const [categoryType, setCategoryType] = useState<CategoryKey>(stored.categoryType ?? 'gas-request')
  const [categoryValue, setCategoryValue] = useState(stored.categoryValue ?? 'gasmoneyplease')
  const [showHexResult, setShowHexResult] = useState(stored.showHexResult ?? false)
  const [showCategoryHexResult, setShowCategoryHexResult] = useState(stored.showCategoryHexResult ?? false)
  const [useKeccak, setUseKeccak] = useState(stored.useKeccak ?? true)

  const [working, setWorking] = useState(false)
  const [workSnapshot, setWorkSnapshot] = useState<WorkSnapshot | null>(null)
  const cancelRef = useRef<() => void>(() => {})

  // load persisted tree state once on mount
  useEffect(() => {
    loadTreeNodeState(initialScope)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // if the faucet is not active, force out of gas-request mode (Svelte $effect)
  useEffect(() => {
    if (categoryType === 'gas-request' && !faucetIsActive) {
      setCategoryType('input')
    }
  }, [categoryType, faucetIsActive])

  const categoryByteLength = new TextEncoder().encode(categoryValue).byteLength
  const categoryExceedsLimit = categoryByteLength > 32
  const effectiveUseDirectEncoding = categoryType !== 'gas-request' && !useKeccak && !categoryExceedsLimit
  const hexdText = (isHex(text) ? text : stringToHex(text)).toLowerCase() as Hex

  const oncategoryupdate = (type: CategoryKey, category: string) => {
    const modeChanged = type !== categoryType
    if (type === 'gas-request') {
      if (modeChanged) setUseKeccak(true)
      if (account.address) {
        setText(account.address)
      }
    } else if (modeChanged) {
      setUseKeccak(false)
      setText('')
    }
    setCategoryType(type)
    setCategoryValue(category)
  }

  /**
   * Memoize the worker board on `transportUrl` / chainId / factors so we don't construct a new
   * read client per render (carry-forward from the Task-3 review: `selectClient`/
   * `selectBoardClient` build a NEW client per call — keep them out of hot render paths). The
   * grind is dispatched through `board.addMessage` → the Web Worker seam.
   */
  const board = useMemo(() => {
    if (!transportUrl) return null
    return makeWorkerBoard({
      rpc: transportUrl,
      chainId,
      workMultiplier: globalWorkMultiplier != null ? Number(globalWorkMultiplier) : 1,
      workDivisor: globalWorkDivisor != null ? Number(globalWorkDivisor) : 1,
      onProgress: (msg) => {
        const { stats } = msg
        useTerminalStore
          .getState()
          .printToTerminal(new Log(`progress ${stats.iterations} over ${stats.duration}ms`))
        useTerminalStore.getState().updateProgress(stats)
      },
      workerFactory,
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [transportUrl, chainId, globalWorkMultiplier, globalWorkDivisor, workerFactory])

  const workAndSend = async () => {
    if (!transportUrl || !board) return
    setWorking(true)
    const category = (
      effectiveUseDirectEncoding ? stringToHex(categoryValue, { size: 32 }) : keccak256(stringToHex(categoryValue))
    ) as Hex
    setWorkSnapshot({
      chainName,
      chainId,
      rpc: fullTransportUrl ?? transportUrl,
      categoryType,
      categoryValue,
      categoryEncoding: effectiveUseDirectEncoding ? 'direct' : 'keccak256',
      categoryHex: category,
      messageText: text,
      messageHex: hexdText,
      messageByteLength: (hexdText.length - 2) / 2,
    })
    try {
      // the grind + post both run INSIDE the worker (Task-2 seam folds `send` into the worker)
      await board.addMessage({ category, data: hexdText })
      setWorkSnapshot(null)
      await new Promise((resolve) => setTimeout(resolve, 1000))
      await useChainStore.getState().loadContent()
    } catch (err) {
      if (err) console.error(err)
    } finally {
      cancelRef.current = () => {}
      setWorking(false)
    }
  }

  const setInputValue = (value: string) => {
    setText(value)
    if (categoryType === 'gas-request') {
      if (isAddress(value)) account.setAddress(value as Hex)
    } else {
      account.setAddress(null)
    }
  }
  const setRandomText = () => setText(keccak256(numberToHex(Date.now())))

  const disabled = working || !rpcValid
  const submitDisabled = disabled || (categoryType === 'gas-request' && !isAddress(text))

  // persist interactive state on change (Svelte $effect)
  useEffect(() => {
    const scope = scopeFromStore()
    save(scope, 'interactive', {
      categoryType,
      categoryValue,
      text,
      showHexResult,
      showCategoryHexResult,
      useKeccak,
    } satisfies InteractiveState)
  }, [categoryType, categoryValue, text, showHexResult, showCategoryHexResult, useKeccak])

  // derive the render tree from the store's message list
  const tree = useMemo(
    () =>
      toTree({
        list: selectMessageList(),
        latestBlockNumber: latestBlockNumber ?? undefined,
        globalFactors:
          globalWorkMultiplier != null && globalWorkDivisor != null
            ? { workMultiplier: globalWorkMultiplier, workDivisor: globalWorkDivisor }
            : null,
      }),
    [content, latestBlockNumber, globalWorkMultiplier, globalWorkDivisor],
  )

  // prune stale TreeView entries when content changes
  useEffect(() => {
    if (!tree.children.length) return
    pruneTreeNodeState(collectLabels(tree.children))
  }, [tree])

  return (
    <div className="flex flex-col max-w-5xl pb-4 px-4 mx-auto w-full bg-white dark:bg-gray-950 lg:rounded-2xl shadow-sm gap-4">
      <div className="flex flex-col grow justify-center items-center">
        <div id="interactive" className="flex w-full grow flex-col">
          <SelectChain
            onChange={(e) => {
              useChainStore.getState().setChainOption(e.target.value as ChainOption)
            }}
          />
          <div className="container flex flex-col md:flex-row max-w-5xl items-start gap-4 justify-center grow">
            <div className="container flex flex-col p-3 gap-2 rounded-lg border border-gray-300 dark:border-gray-600 shadow bg-gray-50 dark:bg-gray-900">
              <div className="container m-auto flex-col flex">
                <Category
                  type={categoryType}
                  value={categoryValue}
                  oncategoryupdate={oncategoryupdate}
                  disabled={disabled}
                  cancel={() => cancelRef.current()}
                  working={working}
                  showHexResult={showCategoryHexResult}
                  onToggleShowHex={setShowCategoryHexResult}
                  useKeccak={useKeccak}
                  categoryExceedsLimit={categoryExceedsLimit}
                  onToggleKeccak={setUseKeccak}
                />
              </div>
              <div className="container m-auto flex flex-col text-center">
                <MessageInput
                  disabled={disabled}
                  text={text}
                  onChange={setInputValue}
                  type={categoryType}
                  setToRandom={setRandomText}
                  showHexResult={showHexResult}
                  onToggleShowHex={setShowHexResult}
                  balance={account.balance}
                  gasSymbol={account.gasSymbol}
                />
              </div>
              <div className="container m-auto flex flex-row justify-between">
                <PresetButtons workAndSend={workAndSend} disabled={submitDisabled} />
              </div>
            </div>
            <div className="container flex flex-col mx-auto md:max-w-sm align-top overflow-hidden">
              <Terminal working={!!working} />
            </div>
          </div>
          <RequestSnapshot
            snapshot={workSnapshot}
            working={working}
            onClose={() => {
              cancelRef.current()
              setWorkSnapshot(null)
            }}
          />
        </div>
      </div>
      <div className="flex flex-col relative">
        {loading && (
          <div className="absolute inset-0 z-10 flex items-center justify-center bg-white/70 dark:bg-gray-900/70 rounded-lg backdrop-blur-[1px] transition-opacity duration-200">
            <div className="flex flex-col items-center gap-2">
              <svg
                className="animate-spin h-6 w-6 text-gray-400"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                ></path>
              </svg>
              <span className="text-sm text-gray-500 dark:text-gray-400 font-mono">Loading…</span>
            </div>
          </div>
        )}
        <Summary />
        <TreeView childrenNodes={tree.children} label="Message Board" isRoot hideContent />
      </div>
    </div>
  )
}

// packages/ui/src/components/Interactive.svelte
<script lang="ts">
  import { numberToHex, isHex, stringToHex, isAddress, type Hex, keccak256 } from 'viem'

  import { account } from '../lib/web3.svelte'
  import { toTree, terminalState } from '../lib/log.svelte'
  import * as board from '../lib/msgboard.svelte'
  import Summary from './Summary.svelte'
  import MessageInput from '../components/MessageInput.svelte'
  import Category from '../components/Category.svelte'
  import PresetButtons from '../components/PresetButtons.svelte'
  import TreeView, { loadTreeNodeState, pruneTreeNodeState } from '../components/TreeView.svelte'
  import Terminal from '../components/Terminal.svelte'
  import SelectChain from './SelectChain.svelte'
  import RequestSnapshot from './RequestSnapshot.svelte'
  import type { ChainOption } from '../lib/rpc.svelte'
  import { getScope, load, save, collectLabels } from '../lib/persist.svelte'

  type CategoryKey = 'gas-request' | 'input'
  /** shape of the Interactive component's persisted UI state */
  type InteractiveState = {
    categoryType: CategoryKey
    categoryValue: string
    text: string
    showHexResult: boolean
    showCategoryHexResult: boolean
    useKeccak: boolean
  }

  const initialScope = getScope()
  const stored = load<Partial<InteractiveState>>(initialScope, 'interactive', {})
  loadTreeNodeState(initialScope)

  let text = $state(stored.text ?? '')
  let categoryType: CategoryKey = $state(stored.categoryType ?? 'gas-request')
  let categoryValue = $state(stored.categoryValue ?? 'gasmoneyplease')

  // reload all persisted state when the chain scope changes
  let prevScope = initialScope
  $effect(() => {
    const scope = getScope()
    if (scope === prevScope) return
    prevScope = scope
    const state = load<Partial<InteractiveState>>(scope, 'interactive', {})
    categoryType = state.categoryType ?? 'gas-request'
    categoryValue = state.categoryValue ?? 'gasmoneyplease'
    text = state.text ?? ''
    showHexResult = state.showHexResult ?? false
    showCategoryHexResult = state.showCategoryHexResult ?? false
    useKeccak = state.useKeccak ?? true
    loadTreeNodeState(scope)
  })

  $effect(() => {
    if (categoryType === 'gas-request' && !board.chain.faucetIsActive) {
      categoryType = 'input'
    }
  })
  /** Frozen snapshot of data inputs captured at the moment work begins */
  type WorkSnapshot = {
    chainName: string
    chainId: number
    rpc: string
    categoryType: CategoryKey
    categoryValue: string
    categoryEncoding: 'keccak256' | 'direct'
    categoryHex: string
    messageText: string
    messageHex: string
    messageByteLength: number
  }

  let working = $state(false)
  let workSnapshot = $state<WorkSnapshot | null>(null)
  let cancel = $state(() => {})
  let showHexResult = $state(stored.showHexResult ?? false)
  let showCategoryHexResult = $state(stored.showCategoryHexResult ?? false)
  /** when true, category is keccak256 hashed to 32 bytes; when false, direct utf8→hex zero-padded */
  let useKeccak = $state(stored.useKeccak ?? true)
  const categoryByteLength = $derived(new TextEncoder().encode(categoryValue).byteLength)
  /** category exceeds the 32-byte limit and must be hashed via keccak256 */
  const categoryExceedsLimit = $derived(categoryByteLength > 32)
  /** resolved encoding: direct hex only when in input mode, keccak is off, and category fits in 32 bytes */
  const effectiveUseDirectEncoding = $derived(categoryType !== 'gas-request' && !useKeccak && !categoryExceedsLimit)
  const onToggleShowHex = (show: boolean) => {
    showHexResult = show
  }
  const onToggleCategoryHexResult = (show: boolean) => {
    showCategoryHexResult = show
  }

  const hexdText = $derived((isHex(text) ? text : stringToHex(text)).toLowerCase())

  const oncategoryupdate = (type: CategoryKey, category: string) => {
    const modeChanged = type !== categoryType
    if (type === 'gas-request') {
      if (modeChanged) useKeccak = true
      if (account.address) {
        text = account.address
        account.updateBalance()
      }
    } else {
      if (modeChanged) {
        useKeccak = false
        text = ''
      }
    }
    categoryType = type
    categoryValue = category
  }
  const setToAddress = (txt: string) => {
    account.address = txt as Hex
    text = txt
    account.updateBalance()
  }
  const workAndSend = async () => {
    const rpc = board.chain.transportUrl
    if (!rpc) return
    working = true
    const category = effectiveUseDirectEncoding
      ? stringToHex(categoryValue, { size: 32 })
      : categoryValue
    // freeze current data inputs so the user can inspect what was submitted
    workSnapshot = {
      chainName: board.chain.name ?? 'Unknown',
      chainId: board.chain.chain?.id ?? 0,
      rpc: board.chain.fullTransportUrl ?? rpc,
      categoryType,
      categoryValue,
      categoryEncoding: effectiveUseDirectEncoding ? 'direct' : 'keccak256',
      categoryHex: effectiveUseDirectEncoding
        ? stringToHex(categoryValue, { size: 32 })
        : keccak256(stringToHex(categoryValue)),
      messageText: text,
      messageHex: hexdText,
      messageByteLength: (hexdText.length - 2) / 2,
    }
    try {
      const worker = await board.doWork(rpc, category, hexdText)
      cancel = worker.cancel
      const work = await worker.start()
      await board.send(rpc, work)
      workSnapshot = null
      await new Promise((resolve) => setTimeout(resolve, 1000))
      await board.chain.loadContent()
    } catch (err) {
      if (err) console.error(err)
    } finally {
      cancel = () => {}
      working = false
    }
  }
  const setInputValue = (value: string) => {
    text = value
    if (categoryType === 'gas-request') {
      if (!isAddress(text)) {
        return
      }
      setToAddress(text)
    } else {
      account.address = null
    }
  }
  const setRandomText = () => {
    text = keccak256(numberToHex(Date.now()))
  }
  const disabled = $derived(working || !board.chain.rpcValid)
  const submitDisabled = $derived(disabled || (categoryType === 'gas-request' && !isAddress(text)))

  // persist interactive state to chain-scoped localStorage on every change
  $effect(() => {
    const scope = getScope()
    save(scope, 'interactive', {
      categoryType,
      categoryValue,
      text,
      showHexResult,
      showCategoryHexResult,
      useKeccak,
    } satisfies InteractiveState)
  })

  // derive tree once for rendering and pruning
  const tree = $derived(toTree({
    list: terminalState.messageList,
    latestBlockNumber: board.chain.latestBlockNumber ?? undefined,
    globalFactors: board.chain.globalWorkMultiplier != null && board.chain.globalWorkDivisor != null
      ? { workMultiplier: board.chain.globalWorkMultiplier, workDivisor: board.chain.globalWorkDivisor }
      : null,
  }))

  // prune stale TreeView entries when content changes
  $effect(() => {
    if (!tree.children.length) return
    const validLabels = collectLabels(tree.children)
    pruneTreeNodeState(validLabels)
  })
</script>

<div class="flex flex-col max-w-5xl pb-4 px-4 mx-auto w-full bg-white dark:bg-gray-950 lg:rounded-2xl shadow-sm gap-4">
  <div class="flex flex-col grow justify-center items-center">
    <div id="interactive" class="flex w-full grow flex-col">
      <SelectChain onchange={(e) => {
        const target = e.target as HTMLSelectElement
        const chain = target.value as ChainOption
        board.chain.chainOption = chain
      }} />
      <div class="container flex flex-col md:flex-row max-w-5xl items-start gap-4 justify-center grow">
        <div class="container flex flex-col p-3 gap-2 rounded-lg border border-gray-300 dark:border-gray-600 shadow bg-gray-50 dark:bg-gray-900">
          <div class="container m-auto flex-col flex">
            <Category
              type={categoryType}
              value={categoryValue}
              {oncategoryupdate}
              {disabled}
              {cancel}
              {working}
              showHexResult={showCategoryHexResult}
              onToggleShowHex={onToggleCategoryHexResult}
              {useKeccak}
              {categoryExceedsLimit}
              onToggleKeccak={(kec) => { useKeccak = kec }}
            />
          </div>
          <div class="container m-auto flex flex-col text-center">
            <MessageInput {disabled} {text} onchange={setInputValue} type={categoryType} setToRandom={setRandomText} {showHexResult} {onToggleShowHex} />
          </div>
          <div class="container m-auto flex flex-row justify-between">
            <PresetButtons {workAndSend} disabled={submitDisabled} />
          </div>
        </div>
        <div class="container flex flex-col mx-auto md:max-w-sm align-top overflow-hidden">
          <Terminal working={!!working} />
        </div>
      </div>
      <RequestSnapshot snapshot={workSnapshot} {working} onclose={() => { cancel(); workSnapshot = null }} />
    </div>
  </div>
  <div class="flex flex-col relative">
    {#if board.chain.loading}
      <div class="absolute inset-0 z-10 flex items-center justify-center bg-white/70 dark:bg-gray-900/70 rounded-lg backdrop-blur-[1px] transition-opacity duration-200">
        <div class="flex flex-col items-center gap-2">
          <svg class="animate-spin h-6 w-6 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
          </svg>
          <span class="text-sm text-gray-500 dark:text-gray-400 font-mono">Loading&hellip;</span>
        </div>
      </div>
    {/if}
    <Summary />
    <TreeView children={tree.children} label="Message Board" isRoot hideContent />
  </div>
</div>
