// packages/ui/src/pages/Home.svelte
<script lang="ts">
  import Welcome from '../components/Welcome.svelte'
  import FullScreen from '../components/FullScreen.svelte'
  import SalesPitch from '../components/SalesPitch.svelte'
  import ProtocolComparison from '../components/ProtocolComparison.svelte'
  import Interactive from '../components/Interactive.svelte'
  import NextSteps from '../components/NextSteps.svelte'
  import Footer from '../components/Footer.svelte'
  import Docs from '../components/Docs.svelte'
  import UseCases from '../components/UseCases.svelte'
  import JoinNetwork from '../components/JoinNetwork.svelte'
  import GamesCallout from '../components/GamesCallout.svelte'
  import SideToc from '../components/SideToc.svelte'

  const sections = [
    { id: 'overview', label: 'Overview' },
    { id: 'try-it', label: 'Try it' },
    { id: 'use-cases', label: 'Use cases' },
    { id: 'games', label: 'Games' },
    { id: 'api', label: 'API' },
    { id: 'network', label: 'Network' },
    { id: 'compare', label: 'Compare' },
    { id: 'next-steps', label: 'Next steps' },
  ]
</script>

<SideToc {sections} />

<section id="top"><Welcome /></section>
<section id="overview" class="scroll-mt-16"><SalesPitch /></section>
<section id="try-it" class="scroll-mt-16">
  <FullScreen id="interactive-container" class="flex bg-gray-50 dark:bg-gray-900 w-full flex-row items-center justify-center shadow">
    <Interactive />
  </FullScreen>
</section>
<section id="use-cases" class="scroll-mt-16"><UseCases /></section>
<section id="games" class="scroll-mt-16"><GamesCallout /></section>
<section id="api" class="scroll-mt-16"><Docs /></section>
<section id="network" class="scroll-mt-16"><JoinNetwork /></section>
<section id="compare" class="scroll-mt-16"><ProtocolComparison /></section>
<section id="next-steps" class="scroll-mt-16"><NextSteps /></section>
<Footer />

// packages/ui/src/pages/Home.tsx
import { Welcome } from '../components/Welcome'
import { FullScreen } from '../components/FullScreen'
import { SalesPitch } from '../components/SalesPitch'
import { ProtocolComparison } from '../components/ProtocolComparison'
import { Interactive } from '../components/Interactive'
import { NextSteps } from '../components/NextSteps'
import { Footer } from '../components/Footer'
import { Docs } from '../components/Docs'
import { UseCases } from '../components/UseCases'
import { JoinNetwork } from '../components/JoinNetwork'
import { GamesCallout } from '../components/GamesCallout'
import { SideToc } from '../components/SideToc'

const sections = [
  { id: 'overview', label: 'Overview' },
  { id: 'try-it', label: 'Try it' },
  { id: 'use-cases', label: 'Use cases' },
  { id: 'games', label: 'Games' },
  { id: 'api', label: 'API' },
  { id: 'network', label: 'Network' },
  { id: 'compare', label: 'Compare' },
  { id: 'next-steps', label: 'Next steps' },
]

/** Ported from `pages/Home.svelte` — the landing layout. */
export function Home() {
  return (
    <>
      <SideToc sections={sections} />

      <section id="top">
        <Welcome />
      </section>
      <section id="overview" className="scroll-mt-16">
        <SalesPitch />
      </section>
      <section id="try-it" className="scroll-mt-16">
        <FullScreen
          id="interactive-container"
          className="flex bg-gray-50 dark:bg-gray-900 w-full flex-row items-center justify-center shadow">
          <Interactive />
        </FullScreen>
      </section>
      <section id="use-cases" className="scroll-mt-16">
        <UseCases />
      </section>
      <section id="games" className="scroll-mt-16">
        <GamesCallout />
      </section>
      <section id="api" className="scroll-mt-16">
        <Docs />
      </section>
      <section id="network" className="scroll-mt-16">
        <JoinNetwork />
      </section>
      <section id="compare" className="scroll-mt-16">
        <ProtocolComparison />
      </section>
      <section id="next-steps" className="scroll-mt-16">
        <NextSteps />
      </section>
      <Footer />
    </>
  )
}
